{
  "formatVersion": "1.1",
  "component": {
    "group": "com.panyukovn",
    "module": "logging-starter-gradle",
    "version": "1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-gradle-1.2-SNAPSHOT.jar",
          "url": "logging-starter-gradle-1.2-SNAPSHOT.jar",
          "size": 8516,
          "sha512": "f8397dd664b7f5f08715d7d78d8637e0a8627dd5b0da1bf83b91edd47cdbd2142f3f9aeb3f760f82320e1a84a64b50b4daca92cc3959f3fed5a6c4330863a92d",
          "sha256": "8ef639dd57203cdea50b6518a281514105f6921d7f852d7ed0afc6de711f0aa0",
          "sha1": "82a6f0e4c7ab243a1c6480261d65d947ac0654eb",
          "md5": "9fc147ff6612facdfe95f26523dbf46e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-gradle-1.2-SNAPSHOT.jar",
          "url": "logging-starter-gradle-1.2-SNAPSHOT.jar",
          "size": 8516,
          "sha512": "f8397dd664b7f5f08715d7d78d8637e0a8627dd5b0da1bf83b91edd47cdbd2142f3f9aeb3f760f82320e1a84a64b50b4daca92cc3959f3fed5a6c4330863a92d",
          "sha256": "8ef639dd57203cdea50b6518a281514105f6921d7f852d7ed0afc6de711f0aa0",
          "sha1": "82a6f0e4c7ab243a1c6480261d65d947ac0654eb",
          "md5": "9fc147ff6612facdfe95f26523dbf46e"
        }
      ]
    }
  ]
}
